ecell/ecell4_base

CMakeLists.txt, appveyor.yml, readthedocs/conf.py, requirements.txt
and add Python3 64bit support for Windows
=> update version 4.0.5

appveyor.yml
=> chore(appveyor.yml): add Python36 support for Windows

python/CMakeLists.txt
=> Parallel build

ecell4/core/LatticeSpaceVectorImpl.cpp, ecell4/core/tests/LatticeSpace_test.cpp
=> fix: Fix a null pointer bug

.travis.yml
A patch fixing https://github.com/ecell/ecell4/issues/219
=> Use the default path to call Python

ecell4/egfrd/EGFRDSimulator.hpp
=> use k_tot and choose reaction rule

python/lib/ecell4/extra/ensemble.py, python/lib/ecell4/extra/slurm.py
=> Add run_slurm

appveyor.yml, circle.yml
v2 and the old v3s are optionally supported only on Linux. #265
=> ci: Only support Python the latest v3 64bit

appveyor.yml, circle.yml
=> Revert "ci: Only support Python the latest v3 64bit"

.circleci/config.yml, .gitmodules
I just re-created "greens_functions" git submodule.
I don't know why this fixes the circleci error.
=> This fix circleci checkout problem

appveyor.yml, python/setup.py.in
This is a fix for #300. Link gsl libraries statically.
=> Use gsl:x64-windows-static

ecell4/bd/tests/BDSimulator_test.cpp, ecell4/core/CMakeLists.txt, ecell4/core/LatticeSpaceCellListImpl.hpp, ecell4/core/LatticeSpaceVectorImpl.cpp, ecell4/core/Quantity.hpp, ecell4/core/ReactionRule.cpp, ecell4/core/ReactionRule.hpp, ecell4/core/ReactionRuleDescriptor.hpp, ecell4/core/Species.cpp, ecell4/core/Species.hpp, ecell4/core/VacantType.hpp, ecell4/core/tests/LatticeSpace_test.cpp, ecell4/core/tests/OffLatticeSpace_test.cpp, ecell4/core/tests/Species_test.cpp, ecell4/egfrd/samples/mymapk.cpp, ecell4/egfrd/samples/polygon.cpp, ecell4/meso/samples/simple-meso.cpp, ecell4/spatiocyte/samples/diffusion.cpp, ecell4/spatiocyte/samples/simple_lattice.cpp, ecell4/spatiocyte/tests/SpatiocyteSimulator_test.cpp, ecell4/spatiocyte/tests/SpatiocyteWorld_test.cpp, python/lib/ecell4/ReactionRule.pxi, python/lib/ecell4/Species.pxi, python/lib/ecell4/core.pxd, python/lib/ecell4/util/decorator.py, python/lib/ecell4/util/model_parser.py, python/lib/ecell4/util/parseobj.py
Enable to store units in Model.
=> Enable Quantity in Model

.travis.yml, CMakeLists.txt, ecell4/egfrd/Multi.hpp, ecell4/egfrd/ParticleTraits.hpp, python/setup.py.in
- Fix PYTHONPATH
- Fix unittest
- Avoid ADL calls in egfrd
=> fix: Avoid improper ADL (#312)

ecell4/core/SubvolumeSpace.hpp, ecell4/meso/MesoscopicWorld.hpp, python/lib/ecell4_base/meso.pxd, python/lib/ecell4_base/meso.pyx
=> Add an interface to get numbers of molecules at once

ecell4/core/extras.cpp, ecell4/core/extras.hpp, ecell4/core/tests/extras_test.cpp
=> #331 Enable the prerelease section

.travis.yml, CMakeLists.txt
- use [FindGSL](https://cmake.org/cmake/help/v3.2/module/FindGSL.html) instead of `find_package`
- fix typo in `.travis.yml`
=> :green_heart: fix conda build on Travis CI

ecell4/core/tests/extras_test.cpp, ecell4/python_api/core.cpp, tests/core/species.py
* Wrap Species::set_attribute for a boolean value
* Test Species::set_attribute more
* Update extras_test
* Add operators to Species
=> Update Species APIs a bit (#359)

.travis.yml
This pull request will make TravisCI build a conda package for Linux.
=> Modify the configuration for TravisCI

ecell4/core/Species.cpp, ecell4/core/Species.hpp, ecell4/python_api/meso.cpp
See https://github.com/ecell/ecell4-base/pull/232
=> Remove temporary std::vector in Species::CopyCtor

.travis.yml
Temporarily disabled, but if you uncomment it, the conda package will be uploaded to Anaconda cloud.
=> Upload Conda package for Linux and OSX

conda.recipe/meta.yaml
This pull request will change the version of our conda package from `v2.0.0b1` to `2.0.0b1`.
=> :wrench: Change the version of the conda package

.circleci/config.yml
* Use CircleCI Workflows and new features of CircleCI 2.1
* Migrate from manylinux1 to manylinux2010
This pull request fixes #387.
=> Improving the configuration for CircleCI

ecell4/core/tests/Halfedge_test.cpp
This fixes a weird error that arises while compiling test code for Polygon by removing type alias.
=> Fix build error on Windows

appveyor.yml, setup.py
The test fails, but I already found the reason why. I also pushed some commits that hopefully fixes it.
=> Running ctest on appveyor

appveyor.yml, conda.recipe/bld.bat
=> Fix AppVeyor build

ecell4/core/Attribute.cpp, ecell4/core/Attribute.hpp, ecell4/core/Quantity.hpp, ecell4/core/ReactionRule.cpp, ecell4/core/ReactionRule.hpp, ecell4/core/Species.cpp, ecell4/core/Species.hpp, ecell4/python_api/core.cpp, tests/core/reaction_rule.py, tests/core/species.py
=> Enable ReactionRule's attributes

.travis.yml, conda.recipe/meta.yaml
And disable the  conda-build for Python37
=> :white_check_mark: Test Python module import in meta.yaml

.circleci/config.yml, LICENSE, conda.recipe/meta.yaml, setup.py
📄 Replace GPLv2 with GPLv3
➖ Remove too much packages
=> 🔖 Bump version to 2.0.1

ecell4/egfrd/StlFileReader.hpp
This causes compilation error in some environment.
=> :bug: fix name lookup in egfrd/StlFileReader

ecell4/python_api/core.cpp, ecell4/python_api/sgfrd.cpp, ecell4/sgfrd/SGFRDWorld.hpp
- add `Triangle` object to `ecell4_base.core`
- add `Triangle SGFRDWorld::get_triangle(const ParticleID&) const;`
=> :sparkles: enable to get a triangle on which a particle locates

conda.recipe/meta.yaml
* Remove needless dependencies
* Introduce the `host` requirements section.
=> Clean up the configuration file of conda-build

ecell4/core/LatticeSpaceVectorImpl.cpp, ecell4/core/OffLatticeSpace.cpp, ecell4/core/OffLatticeSpace.hpp, ecell4/core/VoxelPool.hpp, ecell4/core/tests/OffLatticeSpace_test.cpp, ecell4/python_api/spatiocyte.cpp, ecell4/spatiocyte/OffLattice.hpp, ecell4/spatiocyte/SpatiocyteWorld.cpp, ecell4/spatiocyte/SpatiocyteWorld.hpp, tests/spatiocyte/__init__.py, tests/spatiocyte/offlattice.py
Add the below APIs:
- `spatiocyte.OffLattice`
- `spatiocyte.SpatiocyteWorld.add_offlattice()`
related to #430.
=> Add Python API for OffLattice

ecell4/core/HCPLatticeSpace.cpp, ecell4/core/HCPLatticeSpace.hpp, ecell4/core/LatticeSpaceCellListImpl.cpp, ecell4/core/LatticeSpaceCellListImpl.hpp, ecell4/core/LatticeSpaceHDF5Writer.hpp, ecell4/core/LatticeSpaceVectorImpl.cpp, ecell4/core/LatticeSpaceVectorImpl.hpp, ecell4/core/OffLatticeSpace.cpp, ecell4/core/OffLatticeSpace.hpp, ecell4/core/VoxelSpaceBase.cpp, ecell4/core/VoxelSpaceBase.hpp, ecell4/core/tests/LatticeSpace_test.cpp, ecell4/spatiocyte/OneToManyMap.hpp, ecell4/spatiocyte/ReactionEvent.cpp, ecell4/spatiocyte/SpatiocyteEvent.hpp, ecell4/spatiocyte/SpatiocyteFactory.hpp, ecell4/spatiocyte/SpatiocyteReactions.cpp, ecell4/spatiocyte/SpatiocyteReactions.hpp, ecell4/spatiocyte/SpatiocyteSimulator.cpp, ecell4/spatiocyte/SpatiocyteSimulator.hpp, ecell4/spatiocyte/SpatiocyteWorld.cpp, ecell4/spatiocyte/SpatiocyteWorld.hpp, ecell4/spatiocyte/StepEvent.cpp, ecell4/spatiocyte/Voxel.hpp, ecell4/spatiocyte/utils.cpp, ecell4/spatiocyte/utils.hpp
Refactor and Format sources for spatiocyte
=> Refactor spatiocyte

CMakeLists.txt, conda.recipe/meta.yaml
=> :green_heart: Enable to use system-installed pybind11

.github/workflows/release.yml, exclude_files
=> Add a new CI system for the automatic release

ecell4/core/Polygon.cpp, ecell4/core/geometry.hpp, ecell4/core/tests/Halfedge_test.cpp, ecell4/python_api/core.cpp, ecell4/python_api/sgfrd.cpp, ecell4/sgfrd/Birth.hpp, ecell4/sgfrd/SGFRDFactory.hpp, ecell4/sgfrd/SGFRDSimulator.cpp, ecell4/sgfrd/SGFRDSimulator.hpp, ecell4/sgfrd/SGFRDWorld.cpp, ecell4/sgfrd/SGFRDWorld.hpp, ecell4/sgfrd/ShellContainer.hpp, ecell4/sgfrd/ShellVisitorApplier.hpp, ecell4/sgfrd/StructureRegistrator.hpp
- fix an edge case when pair domain is on an edge
- avoid an edge case around distance on polygon
- enable to handle Birth domain
- remove some other bugs
=> bug fixes and stability improvements in sGFRD

ecell4/core/Model.hpp, ecell4/core/observers.cpp, ecell4/core/observers.hpp, ecell4/python_api/core.cpp
Make observers picklable #250 
NumberObserver, TimingNumberObserver, and FixedIntervalHDF5Observer are picklable.
=> #250 Make observers picklable

setup.py
Now you can build `ecellr4_base` with parallel jobs giving `--jobs` or `-j` option to `build_ext` command.
```console
$ python setup.py build_ext -j 8
```
NOTICE: you can **NOT** use these flags with `build` command instead.
=> :children_crossing: Add a custom option for the parallel build

ecell4/core/Attribute.cpp, ecell4/core/CompartmentSpace.cpp, ecell4/core/LatticeSpaceHDF5Writer.hpp, ecell4/core/NetfreeModel.cpp, ecell4/core/NetworkModel.cpp, ecell4/core/SubvolumeSpace.cpp, ecell4/core/exceptions.hpp, ecell4/meso/MesoscopicWorld.hpp
```cpp
throw_exception<std::invalid_argument>("format ", variables, ", in this way");
```
=> :recycle: add throw_exception

ecell4/core/BDMLWriter.hpp, ecell4/core/CompartmentSpaceHDF5Writer.hpp, ecell4/core/Context.hpp, ecell4/core/LatticeSpaceHDF5Writer.hpp, ecell4/core/ParticleSpaceHDF5Writer.hpp, ecell4/core/Polygon.hpp, ecell4/core/PolygonHDF5Writer.hpp, ecell4/core/SerialIDGenerator.hpp, ecell4/core/SubvolumeSpaceHDF5Writer.hpp, ecell4/sgfrd/BDPropagator.hpp, ecell4/sgfrd/ShellVisitors.hpp, ecell4/sgfrd/distance.hpp, ecell4/sgfrd/distance_calculator.hpp
- `boost::scoped_array<T>` -> `std::unique_ptr<T[]>`
- `boost::array<T, N>` -> `std::array<T, N>`
- `boost/type_traits` -> `<type_traits>`
=> Boost to c++11

conda.recipe/bld.bat, setup.py
remove `Win64` from generator, use `-A x64`
=> :green_heart: fix appveyor build

CMakeLists.txt, ecell4/core/config.h.in, ecell4/core/observers.cpp, ecell4/core/observers.hpp, ecell4/python_api/core.cpp, ecell4/python_api/python_api.hpp
- Enable to pickle observers #250
- Deprecate switching chrono
=> Enable to pickle observers #250

ecell4/core/Triangle.cpp, ecell4/core/tests/CMakeLists.txt, ecell4/core/tests/Triangle_test.cpp
- fix point-triangle distance calculation
- skip most of needless periodic images
- add Triangle_test
=> Fix and speedup distance_point_to_Triangle under PBC

ecell4/core/ParticleSpaceCellListImpl.hpp, ecell4/core/PeriodicRTree.hpp
=> :green_heart: include <array> explicitly

.github/workflows/ccpp.yml
cf. https://github.com/actions/virtual-environments/issues/1811#issuecomment-708480190
=> :green_heart: untap openssl and python2 from brew
