ecell4/bd/BDWorld.hpp, ecell4/core/Species.cpp, ecell4/core/Species.hpp, ecell4/core/tests/Species_test.cpp, ecell4/egfrd/World.hpp, ecell4/meso/MesoscopicWorld.cpp, ecell4/spatiocyte/SpatiocyteWorld.hpp, python/lib/ecell4/Species.pxi, python/lib/ecell4/core.pxd, python/lib/ecell4/util/decorator.py
add #196 Attribute accepts str, float, int, and bool
add #196 list_attributes returns a list of pairs of string and variant
add #196 get_attribute_as_variant -> get_attribute
add #196 decorator supports non-string attributes
add #196 Species constructor rather accepts floats
=> add #196 Store attributes as boost::variant

ecell4/egfrd/Multi.hpp, ecell4/egfrd/ParticleContainer.hpp, ecell4/egfrd/Transaction.hpp, ecell4/egfrd/World.hpp
fix the problem that a particle goes beyond the boundary while Multi::step()
=> override ParticleContainer::apply_structure

ecell4/egfrd/World.hpp
If particle locates exactly on the boundary, World::apply_structure fails. 
Especially, if particle is at the edge of simulation box, it causes stack overflow because of too deep recursion.
changes:
* skip `apply_structure` and use `apply_boundary` if there are no structure in the `World`.
* fix implementation of `apply_structure` to consider "edge case" correctly.
* add more comments.
=> fix: `edge case` in the World::apply_structure.

ecell4/bd/BDWorld.hpp, ecell4/egfrd/World.hpp, python/lib/ecell4/bd.pxd, python/lib/ecell4/egfrd.pxd
Check if a particle has a valid radius in `get_molecule_info`.
=> #282 Raise an exception when a particle with no size is requested

CMakeLists.txt, ecell4/core/Context.cpp, ecell4/core/ReactionRule.cpp, ecell4/core/ReactionRule.hpp, ecell4/core/tests/ReactionRule_test.cpp, ecell4/python_api/core.cpp, ecell4/python_api/egfrd.cpp
The following changes make it compiles on appveyor.
- Define some macros through `CMakeLists.txt`
- `NOMINMAX`
- to prevent macro definition in `<windows.h>`.
- `GSL_DLL`
- required to link GNU Scientific Library on Windows.
- Rename (add prefix `POLICY_`) enumerators in `ReactionRule::policy_type`
- to avoid name conflict with predefined macro, `STRICT`.
- Remove `using namespace ecell4::egfrd` from `python_api/egfrd.cpp`
- the reason is a bit complicated. please see the commit message.
- Update `greens_functions`
- almost the same reason as above.
=> :green_heart: Fix build on appveyor

ecell4/sgfrd/SGFRDSimulator.hpp
The current implementation does not burst domains in `SGFRDSimulator` when the time reaches to `upto`. It causes a problem when used in combination with `FixedIntervalObserver` because locations of particles are not determined.
=> stop SGFRDSimulator at t == upto

conda.recipe/meta.yaml
This PR suppresses some of the warnings while linking.
=> :green_heart: add libraries to conda runtime requirements

ecell4/egfrd/EGFRDSimulator.hpp, ecell4/egfrd/egfrd.hpp
It just suppresses compiler's warnings.
- throw `illegal_state` when control reaches to the unexpected place
- add `override` specifier
=> :rotating_light: suppress warnings while compilation

appveyor.yml
It seems that now `CONDA: 37-x64` works on Appveyor.
=> :construction_worker: use both conda 36 and 37 on appveyor

.travis.yml, ecell4/sgfrd/SGFRDWorld.cpp, ecell4/sgfrd/SGFRDWorld.hpp
Since world.add_molecules() often receives a Species that only has its
serial, some indispensable parameters such taht `radius` and `D` might
be missing. To avoid this inconvenience, it is needed to search species
in the model that is bound to the world.
=> :bug: check bound model before adding molecules

ecell4/sgfrd/BDPropagator.hpp, ecell4/sgfrd/MultiContainer.hpp, ecell4/sgfrd/SGFRDSimulator.cpp, ecell4/sgfrd/SGFRDSimulator.hpp
It looks a bit weird, but it sometimes crashes when it tries to get an attribute from species that is returned from `model.apply_species_attributes` when we call them from python.
=> :bug: never assume Species has attributes

.github/workflows/ccpp.yml
Enable CI tests for `Ubuntu` and `macOS` on Github Actions.
This may replace CI tests on Azure Pipelines.
=> GitHub actions

.github/workflows/ccpp.yml
Fix the problem of failing [the CI with OSX](https://github.com/ecell/ecell4_base/commit/82ab95ffbbe31978048717e160a04098218eabe4/checks?check_suite_id=366159063) on Github Actions.
=> :green_heart: Enforce to run 'brew upgrade' on Github Actions

ecell4/bd/BDSimulator.hpp, ecell4/core/AABBSurface.cpp, ecell4/core/EventScheduler.hpp, ecell4/core/Mesh.cpp, ecell4/core/PlanarSurface.cpp, ecell4/core/collision.cpp, ecell4/core/observers.cpp, ecell4/core/observers.hpp, ecell4/core/shape_operators.hpp, ecell4/core/types.hpp, ecell4/gillespie/GillespieSimulator.cpp, ecell4/meso/MesoscopicSimulator.cpp, ecell4/meso/tests/MesoscopicSimulator_test.cpp, ecell4/ode/ODEFactory.hpp, ecell4/ode/ODESimulator.hpp, ecell4/python_api/core.cpp, ecell4/spatiocyte/ReactionEvent.cpp, ecell4/spatiocyte/SpatiocyteEvent.hpp
This removes the following global constants.
- `ecell4::inf`
- replaced by `std::numeric_limits<Real>::infinity()`
- `ecell4::epsilon`
- replaced by `std::numeric_limits<Real>::epsilon()`
- `ecell4::N_A`
- it seems that it is not used
Currently, `N_A` is not used (except for the python module). But if it would be used somewhere later, I will restore the definition.
=> :fire: remove global constants

azure-pipelines.yml
On Azure, OS X 10.13 seems to have been removed on March 23, 2020. We need to update it.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
=> :green_heart: update OS X on Azure

ecell4/core/Polygon.hpp
=> :recycle: remove macro, it's always C++11

ecell4/core/Polygon.hpp
the macro is already removed. I just forgot to remove this undef.
=> :fire: remove needless undef

ecell4/core/Context.hpp, ecell4/core/ParticleSpaceRTreeImpl.hpp, ecell4/core/tests/CompartmentSpace_test.cpp, ecell4/core/tests/EventScheduler_test.cpp, ecell4/core/tests/LatticeSpace_test.cpp, ecell4/core/tests/OffLatticeSpace_test.cpp, ecell4/core/tests/ParticleSpaceRTreeImpl_test.cpp, ecell4/core/tests/ParticleSpace_test.cpp, ecell4/core/tests/PeriodicRTree_test.cpp, ecell4/core/tests/ReactionRule_test.cpp, ecell4/core/tests/Shape_test.cpp, ecell4/core/tests/SubvolumeSpace_test.cpp, ecell4/sgfrd/SGFRDFactory.hpp, ecell4/sgfrd/SGFRDSimulator.hpp, ecell4/sgfrd/SGFRDWorld.hpp, ecell4/spatiocyte/tests/OneToManyMap_test.cpp, ecell4/spatiocyte/tests/SpatiocyteSimulator_test.cpp, ecell4/spatiocyte/tests/SpatiocyteWorld_test.cpp
- remove deprecated boost.test headers
- `#include <boost/test/test_case_template.hpp>`
- `#include <boost/test/floating_point_comparison.hpp>`
- add missing `override` specifiers
- add paren to `while(ctx = next())` to make sure that `ctx` is the condition
=> :rotating_light: Suppress warnings

ecell4/core/ParticleSpaceRTreeImpl.hpp
- use `throw_exception` instead of `ostringstream`
- implement `particles()` function
=> :recycle: ParticleSpaceRTreeImpl

.circleci/config.yml
It is no longer supported.
https://pythoninsider.blogspot.com/2020/10/python-35-is-no-longer-supported.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+PythonInsider+%28Python+Insider%29
=> :heavy_minus_sign: drop python 3.5 support

azure-pipelines.yml
There seems to be a problem in cpython 3.9.0 that causes UB. To workaround it, we need to update pybind11 to 2.6.0, or just wait until 3.9.1.
=> :arrow_up: update pybind11 from 2.3.0 to 2.6.0
